### ISSUE TITLE
Every collection should has his service?

### ISSUE THREAD

**Issue by evseevnn** [ice-services/moleculer-db#1]
Hi @icebob 
I just start new project and has question about using database with your framework.
How use moleculer-db correctly? I will have many services and some service should take some information from mongo store, but collections can be different. 

How i can see when use this module i should make many services for every collection. No way for use one db service?

**Comment by icebob** [comment]
Hi @evseevnn ,
I don't recommend to use one moleculer-db with many collections. Main concept is, all services stores data in the own DB/collection. Check my [realworld examples](https://github.com/ice-services/moleculer-realworld-example-app) how I use services with collections and use populates. E.g. `articles.author` data is received from `users` collection but via `users` service and not directly.

**Comment by evseevnn** [comment]
Okay. Thank you @icebob!
Your answer been really helpful for me.
